# Generated by Django 3.1.4 on 2021-02-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True)),
                ('From', models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account'), ('Card', 'Card')], max_length=100)),
                ('to', models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account'), ('Card', 'Card')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('bookmark', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True)),
                ('account', models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account'), ('Card', 'Card')], max_length=100)),
                ('category', models.CharField(choices=[('Allowance', 'Allowance'), ('Salary', 'Salary'), ('Self-development', 'Self-development'), ('Petty cash', 'Petty cash'), ('Bonus', 'Bonus'), ('Account', 'Account'), ('Other', 'Other')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('bookmark', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True)),
                ('account', models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account'), ('Card', 'Card')], max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Social Life', 'Social Life'), ('Self-development', 'Self-development'), ('Transportation', 'Transportation'), ('Culture', 'Culture'), ('Household', 'Household'), ('Apparel', 'Apparel'), ('Beauty', 'Beauty'), ('Health', 'Health'), ('Education', 'Education'), ('Gift', 'Gift'), ('others', 'others')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('bookmark', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
